import { Header } from '@/components/Header'
import '../globals.css'
import { Aside } from '@/components/Aside'
import { Title } from '@/components/Title'
import { Metadata } from 'next'

// export const metadata = {
//   title: 'Home | EscolApp',
//   description: 'Generated by create next app',
// }

export const metadata = {
  title:{
    template: '%s | EscolApp',
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" >
      <body className='h-screen flex flex-col justify-between bg-blue-50'>
        {/* //flex flex-1 lg:mt-[5.7em] mt-[6.3em] pb-4 */}
        <Header />
        <main className='flex flex-1 lg:mt-[5.7em] mt-[6.3em] pb-4'>
          <Aside />
          <section className='w-full flex flex-col gap-3 px-3 lg:ml-[9em]'>
            <Title />
            {children}
          </section>
        </main>
      </body>
    </html>
  )
}
